- name: "raspi-config_Wait_for_Network_at_Boot"
  shell: raspi-config nonint do_boot_wait 0
  register: res
- name: "デバッグ"
  debug: var=res.stdout_lines

- name: "raspi-config_Set_Locale"
  shell: raspi-config nonint do_change_locale ja_JP.UTF-8
  register: res
- name: "デバッグ"
  debug: var=res.stdout_lines

- name: "raspi-config_Set_Timezone"
  shell: raspi-config nonint do_change_timezone Asia/Tokyo
  register: res
- name: "デバッグ"
  debug: var=res.stdout_lines

- name: "apt-get update"
  apt:
    update_cache: yes

- name: "apt-get install"
  apt:
    name:
      - ffmpeg
      - pulseaudio
      - pulseaudio-module-bluetooth
      - git
      - jq

- name: "rc.local設定"
  blockinfile:
    dest: /etc/rc.local
    insertbefore: "exit 0"
    content: |
      if [ -d /etc/rc.local.d ]; then
        for i in /etc/rc.local.d/*; do
          if [ -r \$i ]; then
            . \$i
          fi
        done
        unset i
      fi

- name: "ディレクトリ「/etc/bath_radio」作成"
  file:
    path: /etc/bath_radio
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "ディレクトリ「/opt/bath_radio」作成"
  file:
    path: /opt/bath_radio
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "オーディオ設定(pulseaudioサービス化)"
  copy:
    src: pulseaudio.service
    dest: /etc/systemd/system/
    mode: 0644

- name: "オーディオ設定(pulseaudioサービスポリシー設定)"
  copy:
    src: pulseaudio-bluetooth.conf
    dest: /etc/dbus-1/system.d/
    mode: 0644

- name: "setting.sh"
  copy:
    src: setting.sh
    dest: /opt/bath_radio/
    mode: 0755

- name: "update.sh"
  copy:
    src: update.sh
    dest: /opt/bath_radio/
    mode: 0755

- name: "cronファイル"
  copy:
    src: bathradio
    dest: /etc/cron.d/
    mode: 0644

- name: "bltspk_setting.jsonファイル"
  copy:
    src: bltspk_setting.json
    dest: /etc/bath_radio/
    mode: 0666

- name: "region.txtファイル"
  copy:
    src: region.txt
    dest: /etc/bath_radio/
    mode: 0666

- name: "now_station.txtファイル"
  copy:
    src: now_station.txt
    dest: /etc/bath_radio/
    mode: 0666

- name: "オーディオモジュール設定"
  blockinfile:
    dest: /etc/pulse/system.pa
    insertafter: "### Automatically load driver modules for Bluetooth hardware"
    content: |
      .ifexists module-bluetooth-policy.so
      load-module module-bluetooth-policy
      .endif
      .ifexists module-bluetooth-discover.so
      load-module module-bluetooth-discover
      .endif

- name: "radio_coreがある場合は削除"
  shell: "rm -rf radio_core"
  args:
    chdir: /opt
  ignore_errors: yes
  register: res
- name: "デバッグ"
  debug: var=res.stdout_lines

- name: "Git Clone radio_core"
  shell: "git clone https://github.com/NABUKAT/radio_core.git"
  args:
    chdir: /opt
  register: res
- name: "デバッグ"
  debug: var=res.stdout_lines

- name: "定期リブート"
  cron:
    name: Reboot
    minute: "0"
    hour: "14"
    user: root
    job: "/sbin/reboot"
    cron_file: server_reboot

- name: "サーバ再起動"
  reboot:
    reboot_timeout: 60

- name: "サービス起動設定"
  systemd:
    name: pulseaudio
    state: started
    enabled: yes

- name: "音を鳴らすユーザを追加(pi)"
  user:
    name: pi
    groups: pulse-access

- name: "音を鳴らすユーザを追加(root)"
  user:
    name: root
    groups: pulse-access
